### ISSUE TITLE
processor http-output

### ISSUE THREAD

**Issue by vjeantet** [vjeantet/bitfan#17]
Hello @AlexAkulov !

Please when your are ready to push your http-output, use this repo instead of veino/...
I deleted veino organisation as it does not mean anything

Now :
- processors and runtime belong to the same repo
- runtime has been refactored to use only channels only instead of maps.
- processors hava no dependency with runtime "core"

Processor's behavior changed a bit.

Now only one processor starts and its `Receive(e)` method is called concurrently up to the number of workers.

When a processor cannot accept concurent call it should mention it with a ```MaxConcurent() int``` function which returns the max concurrent call the processor can accept.
* return 0 to fix no limit
* return 1 to force processor for receive one event at a time

See [processors/filter-digest](https://github.com/vjeantet/bitfan/blob/master/processors/filter-digest/digest.go) for an example.

**Comment by AlexAkulov** [comment]
ok, thanks

**Comment by vjeantet** [comment]
Thanks fixed with your PR #18
