### ISSUE TITLE
I can't use items of array after mutate split

### ISSUE THREAD

**Issue by AlexAkulov** [vjeantet/bitfan#67]
Hello! 
My usual case is receiving tab-separated line, split, and manipulate items. But in bitfan I can't use items of array after mutate split.

For example:
config:
```
input {
    stdin {}
}
filter {
    mutate {
        split => {"message" => " "}
    }
    mutate {
        add_field => {
            "one" => "%{message[0]}",
            "two" => "%{message[1]}",
            "three" => "%{message.2}",
            "four" => "%{[message][3]}"
        }
    }
}
output {
  stdout {
     codec => rubydebug { }
  }
}

```
output:
```
$ bitfan run
1 2 3 4
{
  "@timestamp": 2017-12-14 13:46:34 Local,
  "tags":       []string{},
  "one":        "[1 2 3 4]",
  "two":        "",
  "three":      "",
  "four":       "",
  "host":       "vm-bitfan1",
  "message":    []string{
    "1",
    "2",
    "3",
    "4",
  },
}
```
Probably it is specific of "github.com/clbanning/mxj", this library supports only maps but not slices.

**Comment by vjeantet** [comment]
I think this is related to a bug on the Split func
Which split and set []string instead of []interface

Mxj knows how to handle []interface

**Comment by vjeantet** [comment]
Will fix this

**Comment by vjeantet** [comment]
fixed

![capture d ecran 2017-12-15 a 00 23 10](https://user-images.githubusercontent.com/1162157/34019277-5b464390-e12e-11e7-8a3f-273e32a67cfb.png)

**Comment by vjeantet** [comment]
Todo : fix tests related to this fix.

**Comment by AlexAkulov** [comment]
Thank you very much!
