### ISSUE TITLE
Self-added fileds "message":"" and "tags":[] 

### ISSUE THREAD

**Issue by OlegYankovic** [vjeantet/bitfan#71]
Use bitfan as a layer between journalbeat and elasticsearch. Bitfan added unwanted by me new fields to log-messages. I am sure that these fileds is not present in journalbeat output and guilty is bitfan. New filed "message":"" appear if my config looks like this:
```
input {
  beats {
    host => ""
    port => 5044
  }
}
output {
  elasticsearch2 {
    host => "localhost"
    port => 9200
  }
  file {
    path => "/tmp/bitfan"
  }
}
```
And new filed "tags":[] appear if add mutate filter to config:
```
filter{
  mutate {
    convert => {"PRIORITY" => "integer"} 
  }
}
```
What's wrong with it? How I can remove it?

**Comment by vjeantet** [comment]
fixed in https://github.com/vjeantet/bitfan/commit/149b186aab6859a94b8875baad413d8c19f864fe and https://github.com/vjeantet/bitfan/commit/a16b0fa250da235680b893741811e39fb7f46cfc
